CREATE TABLE IF NOT EXISTS Users
(
  id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  login VARCHAR(30) NOT NULL,
  email VARCHAR(30) NOT NULL UNIQUE,
  password VARCHAR(60) NOT NULL,
  is_confirm tinyint (1) NOT NULL DEFAULT 0,
  confirm_id BIGINT(1) NOT NULL,
  reg_date TIMESTAMP
);

CREATE TABLE IF NOT EXISTS Images
(
  id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  user_id INT(6) UNSIGNED NOT NULL,
  url VARCHAR(40),
  description TEXT,
  reg_date TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES Users(id) ON UPDATE CASCADE
);